name: Test and Run program

on:
  - push

jobs:
  test-program:
    name: Test Program
    runs-on: ubuntu-lastest
    step:
    - name: Checkout
      user: actions/checkout@v2
    - name: Setup Python
      user: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install pytest
      run: pip install pytest
    - name: Run test cases
      run: pytest tests
  run-program:
    needs: [test-program]
    runs-on: ubuntu-latest
    step:
    - name: checkout
      users: action/checkout@v2
    - name: Setup Python
      users: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run program
      run: python app.py
